# Generated by Django 5.1.1 on 2024-10-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Изображение автомобиля', 'verbose_name_plural': 'Изображения автомобилей'},
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True, help_text='Укажите, доступен ли автомобиль для аренды в данный момент.', verbose_name='Доступен для аренды'),
        ),
    ]
